### ISSUE TITLE
Some unit tests use MPI unnecessarily

### ISSUE THREAD

**Issue by streeve** [LLNL/ExaCA#226]

**Comment by streeve** [comment]
@MattRolchigo fixed in #239 ?

**Comment by MattRolchigo** [comment]
Still have some in tstInitialize.cpp. But once the last 2 structs are created, the unit test reorganization will be complete
